Миннулин Эмиль
stempix/prosoft-c-stack pull request #1
Opened 2023-12-01 07:08 UTC by stempix

All tests were passed.

2023-12-03 12:16 UTC, czertyaka requested changes
Мне очень понравилось решение отделить идентификатор стека от его номера в массиве. Есть несколько небольших замечаний

2023-12-03 12:16 UTC, czertyaka commented on cstack.h
> +struct stack_item
В заголовчный файл это выносить не надо. В нашей библиотеке мы стараемся скрыть реализацию от пользователя. Да и не используются эти структуры тут.

2023-12-03 12:16 UTC, czertyaka commented on cstack.c
> +    memmove(new_stack_item->data, data_in, size);
В C11 появилась более безопасная версия этой функции [`memmove_s`](https://en.cppreference.com/w/c/string/byte/memmove)

2023-12-03 12:16 UTC, czertyaka commented on cstack.h
> +typedef struct stack stack_type;
Старайтесь придерживаться единообразного наименования типов, либо `<name>_t`, либо `<name>_type`

2023-12-03 12:16 UTC, czertyaka commented on cstack.c
> +int find_stack_idx(const hstack_t handler)
Внутренним функциям библиотеки, предназначенным для использования только из этой единицы трансляции, советую обеспечить [internal linkage](https://en.cppreference.com/w/c/language/storage_duration). Тогда у пользователя не будет проблем, если он захочет определить собственную функцию `find_stack_idx`.

Пример без internal linkage:
```
$ cat main.c 
int main() {}

void foo() {}

$ cat foo.c 
int foo() {}

$ cc main.c foo.c
/usr/bin/ld: /tmp/ccrXtvnH.o: in function `foo':
foo.c:(.text+0x0): multiple definition of `foo'; /tmp/ccSdwxT5.o:main.c:(.text+0xb): first defined here
collect2: error: ld returned 1 exit status
```
Пример с internal linkage:
```
$ cat foo.c 
static int foo() {}

$ cc main.c foo.c
```

2023-12-03 12:16 UTC, czertyaka commented on cstack.c
> +        void* data_out = malloc(stack_list.stacks[stack_idx].head->data_size);
Зачем такие сложности? Не проще без лишних аллокаций просто пробежаться по стеку и удалить все фреймы с данными?

2023-12-03 12:16 UTC, czertyaka commented on cstack.c
> +    if (find_stack_idx(hstack) != -1)
Тут лучше бы смотрелся тернарный оператор

2023-12-03 12:16 UTC, czertyaka commented on cstack.c
> +    if (!stack_list.stacks[stack_idx].head) return 0U;
Если удалить эту проверку, ничего не изменится )

2023-12-04 06:12 UTC, stempix commented on cstack.c
> +        void* data_out = malloc(stack_list.stacks[stack_idx].head->data_size);
Здесь хотелось использовать встроенный функционал, но мне это решение сразу не понравилось, не знаю, почему оставил его в таком виде. Изначально была идея еще сделать гибкий метод stack_pop(), чтобы при условии передачи в него аргументов {NULL, 0U} он просто извлекал элемент из стэка, но дойдя до тестов понял, что такое не прокатит)

2023-12-04 06:16 UTC, stempix commented on cstack.h
> +typedef struct stack stack_type;
Старался, но clang где-то в подключенных библиотеках нашел тип stack_t, пришлось заменить наименование. Второй сразу же исправить не додумался.

2023-12-04 07:07 UTC, stempix commented on cstack.c
> +    if (!stack_list.stacks[stack_idx].head) return 0U;
Согласен, видимо на это меня вынудил AddressSanitizer )

2023-12-04 08:50 UTC, stempix commented on cstack.c
> +    memmove(new_stack_item->data, data_in, size);
Ее происхождение связано с, как это описано в [документации](https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/security-features-in-the-crt?view=msvc-170), повышением безопасности использования. Так как в нашей задаче перед применением функции memmove (memcpy) как каждый аргумент проверяется на корректность, так и совокупность передаваемых данной функции параметров также проходит проверку. Соответственно, при применении более безопасной функции все проверки (которые хороши не только для работоспособности, а также для уверенности разработчика в том, что ошибки будут правильно обработаны) являются исчерпывающими. По вышеописанным причинам с моей стороны использование таких функций является неуместным.
P.S.: Компилятор _**clang 10.0.0-4ubuntu1**_ (алиас `__STDC_VERSION__ == 201112L`, что соответствует стандарту **С11**) ругается на неявное объявление этой функции. Поэтому прежде чем рваться искать компилятор, который сможет найти эту функцию, захотелось изучить вопрос рациональности её использования. Надеюсь, мой ответ является достаточным аргументом, и с радостью готов получить фидбэк по нему.

2023-12-04 08:54 UTC, stempix commented on cstack.c
> +int find_stack_idx(const hstack_t handler)
Спасибо за ссылку, очень полезная )

2023-12-04 08:54 UTC, stempix commented on cstack.c
> +    if (find_stack_idx(hstack) != -1)
Согласен, поправил.

2023-12-04 08:57 UTC, stempix commented on cstack.h
> +struct stack_item
Вечный вопрос в моей голове: что должно быть в заголовочнике, а чего нет (думаю на хабре не одна статья посвящена этому, но что-то руки не доходят пошерстить его). Спасибо за отметку, постараюсь изучить данный вопрос глубже.

2023-12-06 18:26 UTC, czertyaka commented
Переименуйте пожалуйста ПР, чтобы в заголовке были имя и фамилия

2023-12-06 18:27 UTC, czertyaka commented on cstack.c
> +    memmove(new_stack_item->data, data_in, size);
Да, уже несколько других студентов обратило мое внимание на то, что `memcpy_s` не входит во все реализации стандартной библиотеки. Так что я не настаиваю на этом изменении)

2023-12-06 18:28 UTC, stempix commented
> Переименуйте пожалуйста ПР, чтобы в заголовке были имя и фамилия

Готово)

2023-12-06 18:32 UTC, czertyaka approved these changes
Задание принято)

2023-12-06 18:32 UTC, czertyaka commented on cstack.h
> +#include <stdlib.h>
Вроде тут этот заголовочный файл не нужен)

2023-12-07 06:48 UTC, merged